# Login and place an order on the website
## **** Asserts the Consent button is visible and clicks it to close the overlay page

def test_example(page: Page) -> None:
    page.goto("https://automationexercise.com/")
    expect(page.get_by_role("button", name="Consent")).to_be_visible()
    page.get_by_role("button", name="Consent").click()
    page.get_by_role("link", name=" Signup / Login").click()
    page.locator("form").filter(has_text="Login").get_by_placeholder("Email Address").click()
    page.locator("form").filter(has_text="Login").get_by_placeholder("Email Address").fill("sparkko@gmail.com")
    page.get_by_role("textbox", name="Password").click()
    page.get_by_role("textbox", name="Password").fill("Testingpassword123")
    page.get_by_role("button", name="Login").click()
    page.get_by_role("link", name=" Men").click()
    page.get_by_role("link", name="Jeans").click()
    expect(page.get_by_role("link", name=" Add to cart").nth(5)).to_be_visible()
    page.get_by_role("link", name=" Add to cart").nth(5).click()
    page.get_by_role("link", name="View Cart").click()
    expect(page.locator("#product-37")).to_contain_text("1")
    page.get_by_text("Proceed To Checkout").click()
    page.get_by_role("link", name="Place Order").click()
    page.locator("input[name=\"name_on_card\"]").click()
    page.locator("input[name=\"name_on_card\"]").fill("Del Test")
    page.locator("input[name=\"card_number\"]").click()
    page.locator("input[name=\"card_number\"]").fill("4444333322221111")
    page.get_by_role("textbox", name="ex.").click()
    page.get_by_role("textbox", name="ex.").fill("000")
    page.get_by_role("textbox", name="MM").click()
    page.get_by_role("textbox", name="MM").fill("12")
    page.get_by_role("textbox", name="YYYY").click()
    page.get_by_role("textbox", name="YYYY").fill("2030")
    page.get_by_role("button", name="Pay and Confirm Order").click()
    expect(page.locator("#form")).to_contain_text("Congratulations! Your order has been confirmed!")
    page.get_by_role("link", name="Continue").click()
    page.get_by_role("link", name=" Logout").click()
    expect(page.get_by_role("heading", name="Login to your account")).to_be_visible()
    expect(page.get_by_role("heading", name="New User Signup!")).to_be_visible()
